actions:
  excluded-workflows:
    - Rebase

deployment:
  environments:
    - name: dev
    - name: test
    - name: staging
  requires:
    - dev
    - test
    - name: live
      requires:
        - staging
  excluded-workflows:
    - Deploy
    - Rebase
