actions:
  excluded-workflows:
    - Rebase

deployment:
  environments:
    - name: dev
    - name: test
      requires:
        - dev
    - name: live
      requires:
        - dev

  excluded-workflows:
    - Deploy
    - Rebase
