name: Deploy

on: [deployment]

jobs:
  deploy:
    name: Deploy my app

    permissions:
      deployments: write

    runs-on: ubuntu-latest

    steps:
      - run: |
          gh api \
          --method POST \
          -H "Accept: application/vnd.github.v3+json" \
          /repos/${{ github.repository_owner }}/${{ github.event.repository.name }}/deployments/${{ github.event.deployment.id }}/statuses \
          -f environment="${{ github.event.deployment.environment }}" \
          -f state="${{ job.status == 'success' && 'success' || 'failure' }}" \
