name: Deploy

on: [deployment]

jobs:
  deploy:
    name: Deploy my app

    permissions:
      deployments: write

    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: moneymeets/moneymeets-composite-actions/set-deployment-status@feature/set-deployment-status-set-log-url
        with:
          environment: ${{ github.event.deployment.environment }}
          state: success
