name: Deploy

on: [deployment]

jobs:
  deploy:
    name: Deploy my app

    permissions:
      deployments: write

    runs-on: ubuntu-latest

    steps:
      - uses: moneymeets/ghd@v2
        with:
          access_token: ${{ github.token }}
          args: set-state --state failure
